using Content.Shared._AU14.Formations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client._AU14.Formations;

[GenerateTypedNameReferences]
public sealed partial class FormationMenuWindow : DefaultWindow
{
    public FormationMenuWindow()
    {
        RobustXamlLoader.Load(this);

        // Load section header icons from the AU14 texture atlas.
        var cache = IoCManager.Resolve<IResourceCache>();
        Texture? TryLoad(string path)
        {
            try { return cache.GetResource<TextureResource>(path).Texture; }
            catch { return null; }
        }

        IconStep1.Texture     = TryLoad("/Textures/_AU14/Interface/icon_step1.png");
        IconStep2.Texture     = TryLoad("/Textures/_AU14/Interface/icon_step2.png");
        IconStep3.Texture     = TryLoad("/Textures/_AU14/Interface/icon_step3.png");
        IconMode.Texture      = TryLoad("/Textures/_AU14/Interface/icon_mode.png");
        IconCollision.Texture = TryLoad("/Textures/_AU14/Interface/icon_collision.png");
        IconDebug.Texture     = TryLoad("/Textures/_AU14/Interface/icon_debug.png");
    }

    public void UpdateState(FormationMenuBuiState state)
    {
        var hasMembers = state.SlottedCount > 0;
        var hasOpenSlots = state.ActiveDotCount > 0;
        var hasPending = state.PendingDots.Count > 0;

        // Status label
        if (state.IsInPlanningMode)
        {
            StatusLabel.Text = "Placement active - click tiles to drop squad markers.";
            StatusLabel.FontColorOverride = Color.Yellow;
        }
        else if (hasMembers)
        {
            StatusLabel.Text = $"Formation active - {state.SlottedCount} member(s) in formation.";
            StatusLabel.FontColorOverride = Color.LimeGreen;
        }
        else if (hasOpenSlots)
        {
            StatusLabel.Text = $"{state.ActiveDotCount} open slot(s) - waiting for soldiers to report in.";
            StatusLabel.FontColorOverride = Color.Cyan;
        }
        else if (hasPending)
        {
            StatusLabel.Text = "Markers staged. Hit Activate when ready.";
            StatusLabel.FontColorOverride = Color.Orange;
        }
        else
        {
            StatusLabel.Text = "No active formation. Start with Step 1.";
            StatusLabel.FontColorOverride = Color.White;
        }

        // Staged marker list
        PendingDotsList.DisposeAllChildren();
        foreach (var dot in state.PendingDots)
        {
            var typeStr = dot.IsLeaderDot ? "[Leader]" : "[Squad]";
            var label = new Label
            {
                Text = $"  {typeStr} ({dot.TileX}, {dot.TileY}) facing {dot.Facing}",
                FontColorOverride = dot.IsLeaderDot ? Color.Gold : Color.Cyan,
            };
            PendingDotsList.AddChild(label);
        }
        if (!hasPending)
            PendingDotsList.AddChild(new Label { Text = "  (none staged)", FontColorOverride = Color.DimGray });

        // Counts footer
        ActiveDotsLabel.Text = $"Open slots: {state.ActiveDotCount}  |  Members: {state.SlottedCount}";

        // Dot lifetime toggle + warning
        DotLifetimeToggleButton.Text = state.ExtendedDotLifetime
            ? "Dot lifetime: Extended (15 min)  [ACTIVE]"
            : "Dot lifetime: Standard (2 min)";
        LifetimeWarningBox.Visible = state.ExtendedDotLifetime;

        // Halt / March (formation starts frozen)
        HaltMarchButton.Text = state.FormationFrozen ? "March Formation" : "Halt Formation";

        // Follow mode (active one is disabled so you can't re-click it)
        ModeHoldButton.Text  = state.FollowMode == FormationFollowMode.Hold  ? "[Active] Hold"  : "Hold";
        ModeChaseButton.Text = state.FollowMode == FormationFollowMode.Chase ? "[Active] Chase" : "Chase";
        ModeHoldButton.Disabled  = !hasMembers || state.FollowMode == FormationFollowMode.Hold;
        ModeChaseButton.Disabled = !hasMembers || state.FollowMode == FormationFollowMode.Chase;

        // Collision toggle
        CollisionToggleButton.Text = state.CollisionsDisabled ? "Collisions: Off" : "Collisions: On";

        // Debug button
        DebugToggleButton.Text = state.DebugShowSlots ? "Hide Slot Positions" : "Show Slot Positions";

        // Enabled states
        ConfirmButton.Disabled = !hasPending;
        CancelPlanningButton.Disabled = !hasPending && !state.IsInPlanningMode;
        UndoLastButton.Disabled = !hasPending;
        ClearAllButton.Disabled = !hasOpenSlots;
        DisbandButton.Disabled = !hasMembers && !hasOpenSlots;
        HaltMarchButton.Disabled = !hasMembers;
        CollisionToggleButton.Disabled = !hasMembers;
        DebugToggleButton.Disabled = !hasMembers;
    }
}
